# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy app source code
COPY . .

# Build the project
RUN npm run build

# Expose any ports if needed (not required for stdio-based MCP)

# Run the MCP server
CMD [ "node", "dist/index.js" ]
